Repository troessner/reek, pull requests merged in 2018-09, with the labels that each got.

#1415 Clean up debugging group in our bundle.
  Gemfile
Labels: internal, ready-for-review

#1418 Update RuboCop dependency
  Gemfile
  docs/templates/default/docstring/setup.rb
  lib/reek/ast/node.rb
  lib/reek/ast/sexp_extensions/methods.rb
  lib/reek/code_comment.rb
  lib/reek/configuration/directory_directives.rb
  lib/reek/configuration/schema_validator.rb
  lib/reek/context/method_context.rb
  lib/reek/context/module_context.rb
  lib/reek/context/visibility_tracker.rb
  lib/reek/context_builder.rb
  lib/reek/detector_repository.rb
  lib/reek/examiner.rb
  lib/reek/report/text_report.rb
  lib/reek/smell_detectors/control_parameter_helpers/call_in_condition_finder.rb
  lib/reek/smell_detectors/control_parameter_helpers/control_parameter_finder.rb
  lib/reek/smell_detectors/duplicate_method_call.rb
  lib/reek/smell_detectors/feature_envy.rb
  lib/reek/smell_detectors/irresponsible_module.rb
  lib/reek/smell_detectors/long_parameter_list.rb
  lib/reek/smell_detectors/manual_dispatch.rb
  lib/reek/smell_detectors/missing_safe_method.rb
  lib/reek/smell_detectors/nested_iterators.rb
  lib/reek/smell_detectors/repeated_conditional.rb
  lib/reek/smell_detectors/too_many_instance_variables.rb
  lib/reek/smell_detectors/too_many_methods.rb
  lib/reek/smell_detectors/too_many_statements.rb
  lib/reek/smell_detectors/uncommunicative_variable_name.rb
  lib/reek/smell_detectors/unused_parameters.rb
  lib/reek/source/source_locator.rb
  lib/reek/spec/should_reek_only_of.rb
  lib/reek/spec/smell_matcher.rb
  lib/reek/tree_dresser.rb
  spec/performance/reek/smell_detectors/runtime_speed_spec.rb
  spec/reek/detector_repository_spec.rb
Labels: ready-for-review

#1413 Simplify todo list feature.
  .simplecov
  README.md
  features/rspec_matcher.feature
  features/todo_list.feature
  lib/reek.rb
  lib/reek/cli/command/todo_list_command.rb
  lib/reek/configuration/app_configuration.rb
  lib/reek/configuration/configuration_converter.rb
  lib/reek/spec/should_reek_of.rb
  spec/reek/cli/command/todo_list_command_spec.rb
  spec/reek/configuration/app_configuration_spec.rb
  spec/reek/configuration/configuration_file_finder_spec.rb
  spec/reek/configuration/schema_validator_spec.rb
  tasks/configuration.rake
Labels: feature, ready-for-review
