Repository troessner/reek, pull requests merged in 2018-06, with the labels that each got.

#1318 Move directory directives under a special key.
  README.md
  features/configuration_files/directory_specific_directives.feature
  lib/reek/configuration/app_configuration.rb
  lib/reek/configuration/directory_directives.rb
  samples/configuration/full_configuration.reek
  spec/reek/configuration/app_configuration_spec.rb
  spec/reek/configuration/directory_directives_spec.rb
Labels: breaking-change, ready-for-review

#1315 Add yml extension to Reeks configuration file.
  .dockerignore
  README.md
  defaults.reek.yml
  docs/API.md
  docs/Basic-Smell-Options.md
  docs/How-To-Write-New-Detectors.md
  docs/Rake-Task.md
  features/configuration_files/directory_specific_directives.feature
  features/configuration_files/warn_about_multiple_configuration_files.feature
  features/configuration_loading.feature
  features/rspec_matcher.feature
  lib/reek/configuration/configuration_file_finder.rb
  lib/reek/configuration/directory_directives.rb
  samples/.reek.yml
  samples/configuration/.reek.yml
  spec/reek/configuration/configuration_file_finder_spec.rb
  tasks/configuration.rake
Labels: breaking-change, ready-for-review

#1335 Fix list output
  lib/reek/cli/options.rb
Labels: ready-for-review

#1332 Replace `wiki-links` flag with `documentation` flag.
  bin/reek
  docs/Command-Line-Options.md
  docs/Reek-Driven-Development.md
  features/command_line_interface/options.feature
  features/reports/json.feature
  features/reports/reports.feature
  features/reports/yaml.feature
  lib/reek/cli/command/report_command.rb
  lib/reek/cli/options.rb
  lib/reek/report.rb
  lib/reek/report/formatter.rb
  lib/reek/report/formatter/documentation_link_warning_formatter.rb
  reek.gemspec
  spec/reek/report/json_report_spec.rb
  spec/reek/report/yaml_report_spec.rb
Labels: breaking-change

#1310 Update AppConfiguration API
  lib/reek/configuration/app_configuration.rb
  lib/reek/spec.rb
Labels: breaking-change, ready-for-review

#1340 Reduce own smell suppressions
  docs/How-To-Write-New-Detectors.md
  lib/reek/smell_detectors/attribute.rb
  lib/reek/smell_detectors/base_detector.rb
  lib/reek/smell_detectors/boolean_parameter.rb
  lib/reek/smell_detectors/class_variable.rb
  lib/reek/smell_detectors/control_parameter.rb
  lib/reek/smell_detectors/data_clump.rb
  lib/reek/smell_detectors/duplicate_method_call.rb
  lib/reek/smell_detectors/feature_envy.rb
  lib/reek/smell_detectors/instance_variable_assumption.rb
  lib/reek/smell_detectors/irresponsible_module.rb
  lib/reek/smell_detectors/long_parameter_list.rb
  lib/reek/smell_detectors/long_yield_list.rb
  lib/reek/smell_detectors/manual_dispatch.rb
  lib/reek/smell_detectors/missing_safe_method.rb
  lib/reek/smell_detectors/module_initialize.rb
  lib/reek/smell_detectors/nested_iterators.rb
  lib/reek/smell_detectors/nil_check.rb
  lib/reek/smell_detectors/repeated_conditional.rb
  lib/reek/smell_detectors/subclassed_from_core_class.rb
  lib/reek/smell_detectors/syntax.rb
  lib/reek/smell_detectors/too_many_constants.rb
  lib/reek/smell_detectors/too_many_instance_variables.rb
  lib/reek/smell_detectors/too_many_methods.rb
  lib/reek/smell_detectors/too_many_statements.rb
  lib/reek/smell_detectors/uncommunicative_method_name.rb
  lib/reek/smell_detectors/uncommunicative_module_name.rb
  lib/reek/smell_detectors/uncommunicative_parameter_name.rb
  lib/reek/smell_detectors/uncommunicative_variable_name.rb
  lib/reek/smell_detectors/unused_parameters.rb
  lib/reek/smell_detectors/unused_private_method.rb
  lib/reek/smell_detectors/utility_function.rb
Labels: ready-for-review

#1333 Generate versioned documentation links
  README.md
  docs/Instance-Variable-Assumption.md
  docs/Uncommunicative-Method-Name.md
  docs/Uncommunicative-Module-Name.md
  docs/Uncommunicative-Parameter-Name.md
  features/command_line_interface/basic_usage.feature
  features/command_line_interface/options.feature
  features/command_line_interface/show_progress.feature
  features/command_line_interface/smell_selection.feature
  features/command_line_interface/smells_count.feature
  features/command_line_interface/stdin.feature
  features/configuration_files/accept_setting.feature
  features/configuration_files/directory_specific_directives.feature
  features/configuration_files/exclude_directives.feature
  features/configuration_files/exclude_paths_directives.feature
  features/configuration_files/masking_smells.feature
  features/configuration_files/mix_accept_reject_setting.feature
  features/configuration_files/reject_setting.feature
  features/configuration_files/unused_private_method.feature
  features/configuration_loading.feature
  features/configuration_via_source_comments/erroneous_source_comments.feature
  features/configuration_via_source_comments/well_formed_source_comments.feature
  features/locales.feature
  features/rake_task/rake_task.feature
  features/reports/json.feature
  features/reports/reports.feature
  features/reports/yaml.feature
  features/samples.feature
  features/support/env.rb
  features/todo_list.feature
  lib/reek/cli/options.rb
  lib/reek/documentation_link.rb
  lib/reek/errors/bad_detector_configuration_key_in_comment_error.rb
  lib/reek/errors/bad_detector_in_comment_error.rb
  lib/reek/errors/garbage_detector_configuration_in_comment_error.rb
  lib/reek/report/code_climate/code_climate_configuration.yml
  lib/reek/report/formatter/documentation_link_warning_formatter.rb
  lib/reek/report/formatter/simple_warning_formatter.rb
  lib/reek/report/json_report.rb
  lib/reek/report/yaml_report.rb
  lib/reek/smell_warning.rb
  spec/reek/documentation_link_spec.rb
  spec/reek/report/json_report_spec.rb
  spec/reek/report/yaml_report_spec.rb
  spec/reek/smell_warning_spec.rb
Labels: ready-for-review

#1345 Remove useless check.
  lib/reek/configuration/configuration_file_finder.rb
Labels: internal, ready-for-review

#1351 Make defaults.reek only relevant as documentation
  .reek.yml
  README.md
  defaults.reek.yml
  docs/Basic-Smell-Options.md
  docs/How-To-Write-New-Detectors.md
  docs/defaults.reek
  features/configuration_files/directory_specific_directives.feature
  lib/reek/configuration/directory_directives.rb
  reek_4_config.reek
  tasks/configuration.rake
Labels: ready-for-review

#1350 Update docs for DuplicateMethodCall.
  docs/Duplicate-Method-Call.md
Labels: documentation

#1361 Use config file error consistently.
  features/configuration_files/directory_specific_directives.feature
  lib/reek/cli/application.rb
  lib/reek/configuration/configuration_file_finder.rb
  lib/reek/configuration/configuration_validator.rb
  lib/reek/errors/config_file_error.rb
  spec/reek/configuration/directory_directives_spec.rb
  spec/reek/configuration/excluded_paths_spec.rb
Labels: internal, ready-for-review

#1360 Refactor rake task to make it more obvious what is happening.
  Rakefile
  tasks/configuration.rake
Labels: internal, ready-for-review

#1364 Fix nonsensical ConfigurationFileFinder specs
  samples/no_config_file/.keep
  spec/reek/configuration/configuration_file_finder_spec.rb
Labels: ready-for-review

#1365 Allow only .reek.yml, not any file ending in .reek.yml
  lib/reek/configuration/configuration_file_finder.rb
  spec/reek/configuration/configuration_file_finder_spec.rb
Labels: breaking-change, ready-for-review

#1347 Refactor samples.
  features/configuration_files/masking_smells.feature
  features/configuration_loading.feature
  features/rspec_matcher.feature
  features/step_definitions/sample_file_steps.rb
  samples/checkstyle.xml
  samples/clean_source/clean.rb
  samples/configuration/.reek.yml
  samples/configuration/home/home.reek.yml
  samples/configuration/non_public_modifiers_mask.reek
  samples/configuration/regular_configuration/.reek.yml
  samples/configuration/regular_configuration/empty_sub_directory/.gitignore
  samples/paths.rb
  samples/smelly_source/inline.rb
  samples/smelly_source/optparse.rb
  samples/smelly_source/redcloth.rb
  samples/smelly_source/smelly.rb
  samples/smelly_with_inline_mask.rb
  samples/smelly_with_modifiers.rb
  samples/source_with_hidden_directories/.hidden/hidden.rb
  samples/source_with_hidden_directories/.hidden/uncommunicative_method_name.rb
  samples/source_with_hidden_directories/not_hidden.rb
  samples/source_with_non_ruby_files/ruby.rb
  samples/source_with_non_ruby_files/uncommunicative_parameter_name.rb
  spec/reek/ast/node_spec.rb
  spec/reek/cli/application_spec.rb
  spec/reek/configuration/app_configuration_spec.rb
  spec/reek/configuration/configuration_file_finder_spec.rb
  spec/reek/configuration/directory_directives_spec.rb
  spec/reek/configuration/excluded_paths_spec.rb
  spec/reek/examiner_spec.rb
  spec/reek/report/xml_report_spec.rb
  spec/reek/source/source_locator_spec.rb
  spec/reek/spec/should_reek_spec.rb
Labels: internal, ready-for-review

#1343 Add support for --stdin-filename
  features/command_line_interface/options.feature
  features/command_line_interface/stdin.feature
  features/step_definitions/reek_steps.rb
  lib/reek/cli/command/report_command.rb
  lib/reek/cli/options.rb
  lib/reek/examiner.rb
  lib/reek/source/source_code.rb
  spec/reek/cli/application_spec.rb
Labels: breaking-change, feature

#1366 Add simple spec to document nil file behavior
  spec/reek/configuration/configuration_file_finder_spec.rb
Labels: ready-for-review

#1370 Remove deprecated Examiner#description
  lib/reek/examiner.rb
  lib/reek/report/formatter.rb
  lib/reek/spec/should_reek_of.rb
  lib/reek/spec/should_reek_only_of.rb
  spec/reek/spec/should_reek_only_of_spec.rb
Labels: ready-for-review

#1368 Improve silently
  lib/reek/ast/node.rb
  lib/reek/cli/silencer.rb
  lib/reek/source/source_code.rb
  spec/reek/cli/silencer_spec.rb
  spec/reek/configuration/directory_directives_spec.rb
  spec/reek/configuration/excluded_paths_spec.rb
  spec/reek/tree_dresser_spec.rb
  spec/spec_helper.rb
Labels: ready-for-review

#1371 Make SourceCode the source of truth for origin
  lib/reek/cli/application.rb
  lib/reek/cli/command/report_command.rb
  lib/reek/cli/options.rb
  lib/reek/examiner.rb
  lib/reek/source/source_code.rb
  spec/reek/cli/application_spec.rb
  spec/reek/source/source_code_spec.rb
Labels: ready-for-review

#1372 Improve YARD documentation
  .yardopts
  docs/yard_plugin.rb
  lib/reek/ast/node.rb
  lib/reek/ast/sexp_extensions/if.rb
  lib/reek/cli/application.rb
  lib/reek/cli/options.rb
  lib/reek/cli/silencer.rb
  lib/reek/code_comment.rb
  lib/reek/configuration/app_configuration.rb
  lib/reek/configuration/configuration_file_finder.rb
  lib/reek/configuration/configuration_validator.rb
  lib/reek/configuration/converter.rb
  lib/reek/configuration/directory_directives.rb
  lib/reek/configuration/excluded_paths.rb
  lib/reek/context/attribute_context.rb
  lib/reek/context/code_context.rb
  lib/reek/context/method_context.rb
  lib/reek/context/module_context.rb
  lib/reek/context_builder.rb
  lib/reek/documentation_link.rb
  lib/reek/examiner.rb
  lib/reek/rake/task.rb
  lib/reek/report/base_report.rb
  lib/reek/report/formatter/heading_formatter.rb
  lib/reek/report/formatter/simple_warning_formatter.rb
  lib/reek/report/xml_report.rb
  lib/reek/smell_detectors/base_detector.rb
  lib/reek/smell_detectors/data_clump.rb
  lib/reek/smell_detectors/duplicate_method_call.rb
  lib/reek/smell_detectors/long_yield_list.rb
  lib/reek/smell_detectors/nested_iterators.rb
  lib/reek/smell_detectors/repeated_conditional.rb
  lib/reek/smell_detectors/uncommunicative_variable_name.rb
  lib/reek/smell_warning.rb
  lib/reek/source/source_locator.rb
  lib/reek/spec.rb
  lib/reek/spec/should_reek_of.rb
  lib/reek/tree_dresser.rb
Labels: ready-for-review

#1359 Scope detectors under a specific key in the configuration.
  docs/defaults.reek
  features/configuration_files/accept_setting.feature
  features/configuration_files/directory_specific_directives.feature
  features/configuration_files/exclude_directives.feature
  features/configuration_files/masking_smells.feature
  features/configuration_files/mix_accept_reject_setting.feature
  features/configuration_files/reject_setting.feature
  features/configuration_files/unused_private_method.feature
  features/configuration_loading.feature
  features/rspec_matcher.feature
  features/todo_list.feature
  lib/reek/cli/command/todo_list_command.rb
  lib/reek/configuration/app_configuration.rb
  lib/reek/configuration/converter.rb
  lib/reek/configuration/default_directive.rb
  lib/reek/spec/should_reek_of.rb
  samples/configuration/accepts_rejects_and_excludes.reek.yml
  samples/configuration/full_configuration.reek
  samples/configuration/full_mask.reek
  samples/configuration/partial_mask.reek
  spec/reek/cli/command/todo_list_command_spec.rb
  spec/reek/configuration/app_configuration_spec.rb
  spec/reek/configuration/configuration_file_finder_spec.rb
  spec/reek/configuration/default_directive_spec.rb
  tasks/configuration.rake
Labels: breaking-change, ready-for-review

#1367 Remove Report::Formatter
  .rubocop.yml
  lib/reek/cli/command/report_command.rb
  lib/reek/report.rb
  lib/reek/report/base_report.rb
  lib/reek/report/documentation_link_warning_formatter.rb
  lib/reek/report/formatter.rb
  lib/reek/report/formatter/documentation_link_warning_formatter.rb
  lib/reek/report/formatter/heading_formatter.rb
  lib/reek/report/formatter/location_formatter.rb
  lib/reek/report/formatter/progress_formatter.rb
  lib/reek/report/formatter/simple_warning_formatter.rb
  lib/reek/report/heading_formatter.rb
  lib/reek/report/location_formatter.rb
  lib/reek/report/progress_formatter.rb
  lib/reek/report/simple_warning_formatter.rb
  lib/reek/report/text_report.rb
  lib/reek/spec/should_reek.rb
  lib/reek/spec/should_reek_only_of.rb
  spec/reek/report/json_report_spec.rb
  spec/reek/report/location_formatter_spec.rb
  spec/reek/report/progress_formatter_spec.rb
  spec/reek/report/text_report_spec.rb
  spec/reek/report/yaml_report_spec.rb
  spec/reek/report_spec.rb
Labels: ready-for-review

#1373 Release reek 4.8.2
  CHANGELOG.md
  lib/reek/version.rb
Labels: ready-for-review

#1362 Validate our configuration by using a schema.
  .rubocop.yml
  features/configuration_files/directory_specific_directives.feature
  features/configuration_files/masking_smells.feature
  features/configuration_files/schema_validation.feature
  features/step_definitions/sample_file_steps.rb
  lib/reek/configuration/configuration_file_finder.rb
  lib/reek/configuration/converter.rb
  lib/reek/configuration/default_directive.rb
  lib/reek/configuration/schema.yml
  lib/reek/configuration/schema_validator.rb
  reek.gemspec
  spec/reek/configuration/schema_validator_spec.rb
Labels: breaking-change, feature, ready-for-review

#1374 Remove support for Ruby 2.2.
  .rubocop.yml
  .travis.yml
  lib/reek/ast/sexp_extensions/methods.rb
  lib/reek/cli/command/todo_list_command.rb
  lib/reek/code_comment.rb
  lib/reek/configuration/app_configuration.rb
  lib/reek/configuration/configuration_file_finder.rb
  lib/reek/documentation_link.rb
  lib/reek/errors/bad_detector_configuration_key_in_comment_error.rb
  lib/reek/errors/bad_detector_in_comment_error.rb
  lib/reek/errors/encoding_error.rb
  lib/reek/errors/garbage_detector_configuration_in_comment_error.rb
  lib/reek/errors/incomprehensible_source_error.rb
  lib/reek/errors/syntax_error.rb
  lib/reek/report/base_report.rb
  lib/reek/smell_configuration.rb
  lib/reek/smell_detectors/base_detector.rb
  lib/reek/smell_detectors/data_clump.rb
  lib/reek/smell_detectors/duplicate_method_call.rb
  lib/reek/smell_detectors/long_parameter_list.rb
  lib/reek/smell_detectors/long_yield_list.rb
  lib/reek/smell_detectors/manual_dispatch.rb
  lib/reek/smell_detectors/nested_iterators.rb
  lib/reek/smell_detectors/repeated_conditional.rb
  lib/reek/smell_detectors/too_many_constants.rb
  lib/reek/smell_detectors/too_many_instance_variables.rb
  lib/reek/smell_detectors/too_many_methods.rb
  lib/reek/smell_detectors/too_many_statements.rb
  lib/reek/smell_detectors/uncommunicative_method_name.rb
  lib/reek/smell_detectors/uncommunicative_module_name.rb
  lib/reek/smell_detectors/uncommunicative_parameter_name.rb
  lib/reek/smell_detectors/uncommunicative_variable_name.rb
  lib/reek/smell_detectors/utility_function.rb
  lib/reek/source/source_code.rb
  lib/reek/version.rb
  reek.gemspec
Labels: breaking-change, ready-for-review

#1378 Convert strings to regexes for directory directives.
  .rubocop.yml
  lib/reek/configuration/configuration_converter.rb
  lib/reek/configuration/configuration_file_finder.rb
  lib/reek/configuration/converter.rb
  lib/reek/configuration/rake_task_converter.rb
  samples/configuration/accepts_rejects_and_excludes_for_detectors.reek.yml
  samples/configuration/accepts_rejects_and_excludes_for_directory_directives.reek.yml
  spec/reek/configuration/configuration_file_finder_spec.rb
  spec/reek/configuration/rake_task_converter_spec.rb
  tasks/configuration.rake
Labels: defect, ready-for-review

#1379 Suppress only warnings from other gems
  lib/reek/ast/node.rb
  lib/reek/cli/silencer.rb
  lib/reek/configuration/schema_validator.rb
  lib/reek/source/source_code.rb
  spec/reek/tree_dresser_spec.rb
  spec/spec_helper.rb
Labels: ready-for-review

#1324 Prepare Reek 5 release.
  CHANGELOG.md
  README.md
  docs/API.md
  docs/Basic-Smell-Options.md
  docs/Code-Smells.md
  docs/Command-Line-Options.md
  docs/How-To-Write-New-Detectors.md
  docs/Missing-Safe-Method.md
  docs/Rake-Task.md
  docs/Reek-4-to-Reek-5-migration.md
  docs/defaults.reek.yml
  features/command_line_interface/options.feature
  features/reports/json.feature
  features/reports/reports.feature
  features/reports/yaml.feature
  features/step_definitions/sample_file_steps.rb
  lib/reek/version.rb
  reek_4_config.reek
  tasks/configuration.rake
Labels: documentation, ready-for-review
